### ISSUE TITLE
Authorization & Authentication

### ISSUE THREAD

**Issue by mahdizahedii2005** [Star-Academy/Summer1403-Project-Group02-Backend#2]
### Tasks 🚀

- [x] Login
- [x] Logout
- [x] Get single user
- [x] Get all user
- [x] Get all Role
- [x] Update user profile info
- [x] Change password
- [x] Registration by Admin
- [x] Add role by Admin
- [x] Delete role by Admin
